# -*- coding: utf-8 -*-
"""Welcome to Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from flask import Flask
app=Flask(__name__)

@app.route('/')
def home():
    return 'Hello world!'
app.run(port=5000)